config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :doctors do
    resources :reviews
  end

  resources :searches

  resources :appointments

  resources :time_slots
  
  root 'searches#new'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <!-- Body Wrapper -->
        <div class="body-wrapper">

<!-- Main Header -->
 <header class="main-header">
                 <div class="wrapper">
                    
                     <%= link_to "", root_path, class: "logo-bookadoc float-left" %>
                     <div class="main-nav float-right">
                        <ul>
                            <% if user_signed_in? %>

                                <li>Welcome <strong><%= current_user.name %></strong>!</li>
                                <li><%= link_to "Log out", signout_path, id: "sign_out", class: "overlap" %></li>
                                <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                                 </li>
                                
                                <% else %>

                                <li>
                                    <a href="#" class="btn join ">Join our Medical Team</a>                           
                                </li>
                                <li>
                                    <%= link_to "LOGIN", new_user_session_path%>|
                                </li>
                                <li>
                                    <%= link_to "SIGN UP", new_user_registration_path%>
                                </li>
                            <% end %>
                        </ul>
                     </div>
                     <div class="clear"></div>
                 </div>
            </header>


<div class="container">
    <%= yield %>
</div>

<!-- Main Footer -->
<footer class="main-footer">
    <section class="section-content footer text-center">
        <div class="wrapper">
            <div class="footer-nav">
                <ul>
                    <li>
                        <a href="#"> About</a>
                    </li>

                    <li>
                        <a href="#"> Doctor Directory</a>
                    </li>
                    <li>
                        <a href="index.html" class="logo-bookadoc"></a>
                    </li>
                    
                    <li>
                        <a href="#"> Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <span>
                Copyright 2016. BOOKADOC. All Rights Reserved.
            </span>
        </div>
    </section>
</footer>



<!-- Modal -->
<div class="modal-overlay">

</div>

</div>

</body>
</html>